public class first {
//    Give the next five pseudorandom numbers generated by the process described
//    on page 113, with a = 12, b = 5, and n = 100, and 92 as the seed for cur.
//See page 113
public static void main(String[] args) {
    int a=12;
    int b=5;
    int n=100;
    int cur=92;
    for (int i = 0; i < 5; i++) {
        int next=(a*cur+b)%n;
        cur=next;
        System.out.println(next);
    }
}
// the output will be (9,13,61,37,49)
}
